(VANAGON-174) Addition of EL-9 platform
Add platforms to support building on el-9 based systems

In CentOS Stream 9

```
dnf install '/bin/mkdir'
Last metadata expiration check: 0:00:09 ago on Thu 02 Dec 2021 12:25:13 PM CET.
No match for argument: /bin/mkdir
Error: Unable to find a match: /bin/mkdir
```

where as

```
dnf install '/usr/bin/mkdir'
```

does install `coreutils-single`

Note that Fedora < 26 has already been deprecated and that case can be
ignored.